import "../styles/globals.css";
import "../styles/toastStyles.css";
import "../styles/Backdrop.css";
import "../styles/Modal.css";
import Head from "next/head";
import HashLoader from "react-spinners/HashLoader";
import ScaleLoader from "react-spinners/ScaleLoader";
import FadeLoader from "react-spinners/FadeLoader";

import { useEffect, useState } from "react";
import { useRouter } from "next/router";
// import { Backdrop } from "@mui/material";
import Backdrop from "./components/Backdrop";

function MyApp({ Component, pageProps }) {
  const [loading, setLoading] = useState(false);
  const router = useRouter();
  useEffect(() => {
    const handleStart = () => {
      setLoading(true);
    };

    const handleComplete = () => {
      setLoading(false);
    };

    router.events.on("routeChangeStart", handleStart);
    router.events.on("routeChangeComplete", handleComplete);
    router.events.on("routeChangeError", handleComplete);

    return () => {
      router.events.off("routeChangeStart", handleStart);
      router.events.off("routeChangeComplete", handleComplete);
      router.events.off("routeChangeError", handleComplete);
    };
  }, [router]);
  return (
    <>
      <Head>
        <title>NBTE Information Portal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Backdrop show={loading} clicked={false} />
      <ScaleLoader
        color="#007F00"
        loading={loading}
        cssOverride={{
          position: "absolute",
          top: "50%",
          left: "50%",
          transform: "translate(-50%, -50%)",
          zIndex: 1000,
        }}
        size={150}
        aria-label="Loading Spinner"
        data-testid="loader"
      />
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
