import "../styles/globals.css";
import "../styles/toastStyles.css";
import "../styles/Backdrop.css";
import "../styles/Modal.css";
import Head from "next/head";
function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>NBTE Information Portal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
