import Head from "next/head";
import Image from "next/image";
import Mast from "./components/Mast";
import Section from "./components/Section";
import Footer from "./components/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>NBTE Information Portal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Mast />
      <Section />
      <Footer />
    </div>
  );
}
